### ISSUE TITLE
Unable to build add-on. SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by groovecoder** [denschub/firefox-tabgroups#16]
## STR:

```
git clone git@github.com:denschub/firefox-tabgroups.git
cd firefox-tabgroups
npm install
./node_modules/.bin/jake run
```
## Expected results:

Firefox should run with the add-on
## Actual results:

```
jake aborted.
/Users/lcrouch/code/firefox-tabgroups/Jakefile:5
const SRC_DIR = "./src";
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadFile (/Users/lcrouch/code/firefox-tabgroups/node_modules/jake/lib/loader.js:81:5)
    at EventEmitter.utils.mixin.run (/Users/lcrouch/code/firefox-tabgroups/node_modules/jake/lib/jake.js:315:35)
    at Object.<anonymous> (/Users/lcrouch/code/firefox-tabgroups/node_modules/jake/bin/cli.js:25:10)
```

**Comment by skyschub** [comment]
Please use Node v5.
